# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
repository:          igorcferreira/PersonalBlog
title:               Igor Ferreira
tagline:             'Um simples blog'
description:         'Um blog escrito por <a href="https://mastodon.social/@igorcferreira">mim</a> sobre coisas'
url:                 https://igorcferreira.com
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Igor Ferreira
  url:               https://mastodon.social/@igorcferreira
  picture:           /public/user_avatar.png

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages: ["pt"]
defaultLang: pt
exclude_from_localizations: ["javascript", "images", "public"]
languagesInfo:
  - key: pt
    name: Português
    message: Ver o site em Português
languageNames:
  pt: Português

feed:
  path: atom.xml
  excerpt_only: false

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'static.json', 'README.md', 'CONTRIBUTING.md', 'LICENSE.md', 'CLAUDE.md', 'AGENTS.md', 'firebase_debug.log']

github:
  repo: https://github.com/igorcferreira/PersonalBlog
